services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal-naramakna
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap:/var/www/bootstrap/cache
    ports:
      - "9000:9000"
    networks:
      - portal-naramakna-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: portal-naramakna-nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portal-naramakna-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: portal-naramakna-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - portal-naramakna-network
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru

networks:
  portal-naramakna-network:
    driver: bridge

volumes:
  app_storage:
    driver: local
  app_bootstrap:
    driver: local
  redis_data:
    driver: local
